### PR TITLE
React group project

### PR DESCRIPTION
**Pull request by bill7pearl**
# In this project my partner @monicah79 and I @bill7pearl have:
- Created React/Redux app.
- Fetched API data for Rockets & Missions and updated the Redux store.
- Dispatched actions to store Rockets & Missions data in the Redux store.
- Used useSelector() Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes.
-  Wrote actions and reducers for reserving/canceling rockets and joining/leaving missions, and displayed "Reserved" & "Cancel reservations" badges for the rockets along with "Active member" & "NOT A MEMBER" badges for the missions.
- Composed column layout and list ONLY the rockets/reserved and missions/joined by the user in My Profile page.
- Used Gitflow.
- Done testing libraries(React Testing Library and Jest).

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @bill7pearl and Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>

You have submitted a project having the linters configuration modified. Kindly ensure that all linter configuration files including `.eslintrc.json` remain as given in the [Microverse linters configuration](https://github.com/microverseinc/linters-config/tree/master/react-redux) repository for react/redux projects.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MaganaAsiati** [comment]
Can you please add also the video link

**Comment by bill7pearl** [comment]
Hello,
Can you please show me where it says it's a requirement to do a video?

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @bill7pearl @monicah79   , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


clap

## Highlights
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] You did a nice job in the implementation and design there is nothing to say however I suggest you improve the way you was giving each other code review, please follow this link to learn more on how to give code review https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md.

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] kindly  Add a descriptive description in your pull request in the future which give more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Cheers and Happy coding!👏👏👏

**Pull request merged**
